"""
common.py — shared utilities for the Instagram sales agent.
"""

from __future__ import annotations

import json
import os
import urllib.parse
from pathlib import Path
from typing import Any

import httpx

GRAPH_URL = "https://graph.facebook.com/v21.0"

IG_ACCESS_TOKEN = os.getenv("IG_ACCESS_TOKEN", "").strip()
IG_BUSINESS_ACCOUNT_ID = os.getenv("IG_BUSINESS_ACCOUNT_ID", "").strip()
FB_PAGE_ID = os.getenv("FB_PAGE_ID", "").strip()
FB_AD_ACCOUNT_ID = os.getenv("FB_AD_ACCOUNT_ID", "").strip()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()

ROOT_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT_DIR / "config"
STATE_DIR = ROOT_DIR / "state"
STATE_DIR.mkdir(exist_ok=True)

PRODUCTS_FILE = CONFIG_DIR / "products.json"
PERSONA_FILE = CONFIG_DIR / "persona.txt"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return default


def save_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def load_config() -> dict[str, Any]:
    return load_json(
        PRODUCTS_FILE,
        {"business_name": "", "products": [], "ads_daily_budget_toman": 0},
    )


def load_persona() -> str:
    if PERSONA_FILE.exists():
        return PERSONA_FILE.read_text(encoding="utf-8")
    return "تو یک دستیار فروش فارسی‌زبان، دوستانه و مودب هستی."


def call_llm(system: str, user_message: str, max_tokens: int = 300) -> str:
    """Calls Gemini (free tier) and returns plain text. Raises on failure."""
    if not GEMINI_API_KEY:
        raise RuntimeError("GEMINI_API_KEY تنظیم نشده است.")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"
    )
    payload = {
        "system_instruction": {"parts": [{"text": system}]},
        "contents": [{"role": "user", "parts": [{"text": user_message}]}],
        "generationConfig": {"maxOutputTokens": max_tokens, "temperature": 0.9},
    }
    resp = httpx.post(url, json=payload, timeout=30.0)
    resp.raise_for_status()
    data = resp.json()
    candidates = data.get("candidates", [])
    if not candidates:
        raise RuntimeError(f"پاسخ نامعتبر از Gemini: {data}")
    parts = candidates[0].get("content", {}).get("parts", [])
    text = "".join(p.get("text", "") for p in parts).strip()
    if not text:
        raise RuntimeError("Gemini پاسخ خالی برگرداند.")
    return text


def pollinations_image_url(prompt: str, width: int = 1024, height: int = 1024) -> str:
    """Returns a direct, publicly-accessible image URL generated by Pollinations (free, no key)."""
    encoded = urllib.parse.quote(prompt)
    seed = abs(hash(prompt)) % 100000
    return (
        f"https://image.pollinations.ai/prompt/{encoded}"
        f"?width={width}&height={height}&seed={seed}&nologo=true"
    )


def graph_get(path: str, **params: Any) -> dict[str, Any]:
    params["access_token"] = IG_ACCESS_TOKEN
    resp = httpx.get(f"{GRAPH_URL}/{path}", params=params, timeout=30.0)
    resp.raise_for_status()
    return resp.json()


def graph_post(path: str, **data: Any) -> dict[str, Any]:
    data["access_token"] = IG_ACCESS_TOKEN
    resp = httpx.post(f"{GRAPH_URL}/{path}", data=data, timeout=30.0)
    resp.raise_for_status()
    return resp.json()
