"""
common.py — shared utilities for the Instagram sales agent.
"""

from __future__ import annotations

import json
import os
import urllib.parse
from pathlib import Path
from typing import Any

import httpx

GRAPH_URL = "https://graph.facebook.com/v21.0"

IG_ACCESS_TOKEN = os.getenv("IG_ACCESS_TOKEN", "").strip()
IG_BUSINESS_ACCOUNT_ID = os.getenv("IG_BUSINESS_ACCOUNT_ID", "").strip()
FB_PAGE_ID = os.getenv("FB_PAGE_ID", "").strip()
FB_AD_ACCOUNT_ID = os.getenv("FB_AD_ACCOUNT_ID", "").strip()

ROOT_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT_DIR / "config"
STATE_DIR = ROOT_DIR / "state"
STATE_DIR.mkdir(exist_ok=True)

PRODUCTS_FILE = CONFIG_DIR / "products.json"
PERSONA_FILE = CONFIG_DIR / "persona.txt"

# Local, open-weight language model (no API key, no geo-restriction —
# it's just a file you download and run yourself).
LLM_MODEL_PATH = os.getenv(
    "LLM_MODEL_PATH",
    str(Path.home() / "models" / "qwen2.5-3b-instruct-q4_k_m.gguf"),
)
_llm_instance = None


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return default


def save_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def load_config() -> dict[str, Any]:
    return load_json(
        PRODUCTS_FILE,
        {"business_name": "", "products": [], "ads_daily_budget_toman": 0},
    )


def load_persona() -> str:
    if PERSONA_FILE.exists():
        return PERSONA_FILE.read_text(encoding="utf-8")
    return "تو یک دستیار فروش فارسی‌زبان، دوستانه و مودب هستی."


def get_llm():
    """Lazily loads the local GGUF model. Requires llama-cpp-python."""
    global _llm_instance
    if _llm_instance is None:
        from llama_cpp import Llama  # imported lazily so other scripts stay light

        if not Path(LLM_MODEL_PATH).exists():
            raise RuntimeError(
                f"فایل مدل در مسیر {LLM_MODEL_PATH} پیدا نشد. "
                "مطمئن شو مرحله دانلود مدل در Workflow قبل از این اسکریپت اجرا شده."
            )
        _llm_instance = Llama(
            model_path=LLM_MODEL_PATH,
            n_ctx=2048,
            n_threads=os.cpu_count() or 2,
            verbose=False,
        )
    return _llm_instance


def call_llm(system: str, user_message: str, max_tokens: int = 300) -> str:
    """Runs the local open-weight model and returns plain text. Raises on failure."""
    llm = get_llm()
    response = llm.create_chat_completion(
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user_message},
        ],
        max_tokens=max_tokens,
        temperature=0.9,
    )
    text = response["choices"][0]["message"]["content"].strip()
    if not text:
        raise RuntimeError("مدل زبانی محلی پاسخ خالی برگرداند.")
    return text


def pollinations_image_url(prompt: str, width: int = 1024, height: int = 1024) -> str:
    """Returns a direct, publicly-accessible image URL generated by Pollinations (free, no key)."""
    encoded = urllib.parse.quote(prompt)
    seed = abs(hash(prompt)) % 100000
    return (
        f"https://image.pollinations.ai/prompt/{encoded}"
        f"?width={width}&height={height}&seed={seed}&nologo=true"
    )


def graph_get(path: str, **params: Any) -> dict[str, Any]:
    params["access_token"] = IG_ACCESS_TOKEN
    resp = httpx.get(f"{GRAPH_URL}/{path}", params=params, timeout=30.0)
    resp.raise_for_status()
    return resp.json()


def graph_post(path: str, **data: Any) -> dict[str, Any]:
    data["access_token"] = IG_ACCESS_TOKEN
    resp = httpx.post(f"{GRAPH_URL}/{path}", data=data, timeout=30.0)
    resp.raise_for_status()
    return resp.json()
